# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rover_pb2 as rover__pb2


class RoverControlStub(object):
    """The service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/rover.RoverControl/GetMap',
                request_serializer=rover__pb2.MapRequest.SerializeToString,
                response_deserializer=rover__pb2.MapResponse.FromString,
                )
        self.GetCommands = channel.unary_stream(
                '/rover.RoverControl/GetCommands',
                request_serializer=rover__pb2.CommandRequest.SerializeToString,
                response_deserializer=rover__pb2.Command.FromString,
                )
        self.GetMineSerial = channel.unary_unary(
                '/rover.RoverControl/GetMineSerial',
                request_serializer=rover__pb2.MineSerialRequest.SerializeToString,
                response_deserializer=rover__pb2.MineSerialResponse.FromString,
                )
        self.ReportExecutionStatus = channel.unary_unary(
                '/rover.RoverControl/ReportExecutionStatus',
                request_serializer=rover__pb2.ExecutionStatusRequest.SerializeToString,
                response_deserializer=rover__pb2.ExecutionStatusResponse.FromString,
                )
        self.SubmitMinePin = channel.unary_unary(
                '/rover.RoverControl/SubmitMinePin',
                request_serializer=rover__pb2.MinePinRequest.SerializeToString,
                response_deserializer=rover__pb2.MinePinResponse.FromString,
                )


class RoverControlServicer(object):
    """The service definition
    """

    def GetMap(self, request, context):
        """1. Get map
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommands(self, request, context):
        """2. Get a stream of commands (server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerial(self, request, context):
        """3. Get a mine serial number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportExecutionStatus(self, request, context):
        """4. Notify if all commands executed successfully
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitMinePin(self, request, context):
        """5. Share a mine PIN with the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoverControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=rover__pb2.MapRequest.FromString,
                    response_serializer=rover__pb2.MapResponse.SerializeToString,
            ),
            'GetCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCommands,
                    request_deserializer=rover__pb2.CommandRequest.FromString,
                    response_serializer=rover__pb2.Command.SerializeToString,
            ),
            'GetMineSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerial,
                    request_deserializer=rover__pb2.MineSerialRequest.FromString,
                    response_serializer=rover__pb2.MineSerialResponse.SerializeToString,
            ),
            'ReportExecutionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportExecutionStatus,
                    request_deserializer=rover__pb2.ExecutionStatusRequest.FromString,
                    response_serializer=rover__pb2.ExecutionStatusResponse.SerializeToString,
            ),
            'SubmitMinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMinePin,
                    request_deserializer=rover__pb2.MinePinRequest.FromString,
                    response_serializer=rover__pb2.MinePinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rover.RoverControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoverControl(object):
    """The service definition
    """

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rover.RoverControl/GetMap',
            rover__pb2.MapRequest.SerializeToString,
            rover__pb2.MapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/rover.RoverControl/GetCommands',
            rover__pb2.CommandRequest.SerializeToString,
            rover__pb2.Command.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMineSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rover.RoverControl/GetMineSerial',
            rover__pb2.MineSerialRequest.SerializeToString,
            rover__pb2.MineSerialResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportExecutionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rover.RoverControl/ReportExecutionStatus',
            rover__pb2.ExecutionStatusRequest.SerializeToString,
            rover__pb2.ExecutionStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitMinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rover.RoverControl/SubmitMinePin',
            rover__pb2.MinePinRequest.SerializeToString,
            rover__pb2.MinePinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
