# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rover.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\x12\x05rover\"2\n\x07MapCell\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"3\n\x07MapData\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x05\"\x1e\n\nMapRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"*\n\x0bMapResponse\x12\x1b\n\x03map\x18\x01 \x01(\x0b\x32\x0e.rover.MapData\"\"\n\x0e\x43ommandRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"\x16\n\x07\x43ommand\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\"?\n\x11MineSerialRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0b\n\x03row\x18\x02 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x03 \x01(\x05\"$\n\x12MineSerialResponse\x12\x0e\n\x06serial\x18\x01 \x01(\t\"?\n\x0eMinePinRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0e\n\x06serial\x18\x02 \x01(\t\x12\x0b\n\x03pin\x18\x03 \x01(\x03\"#\n\x0fMinePinResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"L\n\x16\x45xecutionStatusRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"&\n\x17\x45xecutionStatusResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32\xd5\x02\n\x0cRoverControl\x12/\n\x06GetMap\x12\x11.rover.MapRequest\x1a\x12.rover.MapResponse\x12\x36\n\x0bGetCommands\x12\x15.rover.CommandRequest\x1a\x0e.rover.Command0\x01\x12\x44\n\rGetMineSerial\x12\x18.rover.MineSerialRequest\x1a\x19.rover.MineSerialResponse\x12V\n\x15ReportExecutionStatus\x12\x1d.rover.ExecutionStatusRequest\x1a\x1e.rover.ExecutionStatusResponse\x12>\n\rSubmitMinePin\x12\x15.rover.MinePinRequest\x1a\x16.rover.MinePinResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPCELL._serialized_start=22
  _MAPCELL._serialized_end=72
  _MAPDATA._serialized_start=74
  _MAPDATA._serialized_end=125
  _MAPREQUEST._serialized_start=127
  _MAPREQUEST._serialized_end=157
  _MAPRESPONSE._serialized_start=159
  _MAPRESPONSE._serialized_end=201
  _COMMANDREQUEST._serialized_start=203
  _COMMANDREQUEST._serialized_end=237
  _COMMAND._serialized_start=239
  _COMMAND._serialized_end=261
  _MINESERIALREQUEST._serialized_start=263
  _MINESERIALREQUEST._serialized_end=326
  _MINESERIALRESPONSE._serialized_start=328
  _MINESERIALRESPONSE._serialized_end=364
  _MINEPINREQUEST._serialized_start=366
  _MINEPINREQUEST._serialized_end=429
  _MINEPINRESPONSE._serialized_start=431
  _MINEPINRESPONSE._serialized_end=466
  _EXECUTIONSTATUSREQUEST._serialized_start=468
  _EXECUTIONSTATUSREQUEST._serialized_end=544
  _EXECUTIONSTATUSRESPONSE._serialized_start=546
  _EXECUTIONSTATUSRESPONSE._serialized_end=584
  _ROVERCONTROL._serialized_start=587
  _ROVERCONTROL._serialized_end=928
# @@protoc_insertion_point(module_scope)
